name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:  [18.x]

    env:
      PORT: 3000
      CLIENT_URL: http://127.0.0.1:4444

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Set the sensitive database connection and token secrets
    - name: Set Secrets
      run: |
        echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" >> $GITHUB_ENV
        echo "REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}" >> $GITHUB_ENV
        echo "DATABASE_URI=${{ secrets.DATABASE_URI }}" >> $GITHUB_ENV

    - run: npm ci
    - run: npm run build --if-present

    - run: npm test
